version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    network_mode: "host"
    environment:
      FLASK_ENV: development

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    network_mode: "host"
    hostname: "localhost"
